apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: pod-inventory
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: "cloudcluster.icp:8500/default/inventory"
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 60
          env:
          - name: "spring_datasource_url"
            value: "jdbc:mysql://mysql-lightblue-service:3306/inventorydb" 
          - name: "spring_datasource_username"
            value: "dbuser" 
          - name: "spring_datasource_password"
            value: "Pass4dbUs3R" 
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory
spec:
  type: NodePort
  selector:
    app: inventory
  ports:
   - protocol: TCP
     port: 8080
     nodePort: 30111
